<?xml version="1.0" encoding="utf-8"?><Database Name="MeVaBeDB" Class="MeVaBeDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI;Initial Catalog=MeVaBeDB;Integrated Security=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="MeVaBeDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietGoiSanPham" Member="ChiTietGoiSanPhams">
    <Type Name="ChiTietGoiSanPham">
      <Column Name="maGoiSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="donGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GoiSanPham_ChiTietGoiSanPham" Member="GoiSanPham" ThisKey="maGoiSanPham" OtherKey="maGoiSanPham" Type="GoiSanPham" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietGoiSanPham" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHoaDonSanPham" Member="ChiTietHoaDonSanPhams">
    <Type Name="ChiTietHoaDonSanPham">
      <Column Name="maHoaDon" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="SanPham_ChiTietHoaDonSanPham" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" />
      <Association Name="HoaDon_ChiTietHoaDonSanPham" Member="HoaDon" ThisKey="maHoaDon" OtherKey="maHoaDon" Type="HoaDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuDoiHang" Member="ChiTietPhieuDoiHangs">
    <Type Name="ChiTietPhieuDoiHang">
      <Column Name="maPhieuDoi" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="PhieuDoiHang_ChiTietPhieuDoiHang" Member="PhieuDoiHang" ThisKey="maPhieuDoi" OtherKey="maPhieuDoi" Type="PhieuDoiHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietPhieuDoiHang" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuGiaoHangNhap" Member="ChiTietPhieuGiaoHangNhaps">
    <Type Name="ChiTietPhieuGiaoHangNhap">
      <Column Name="maPhieuGiaoHangNhap" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNhaCungCap" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maPhieuNhap" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="ChiTietPhieuNhap_ChiTietPhieuGiaoHangNhap" Member="ChiTietPhieuNhap" ThisKey="maPhieuNhap,maSanPham,maNhaCungCap" OtherKey="maPhieuNhap,maSanPham,maNhaCungCap" Type="ChiTietPhieuNhap" IsForeignKey="true" />
      <Association Name="PhieuGiaoHangNhap_ChiTietPhieuGiaoHangNhap" Member="PhieuGiaoHangNhap" ThisKey="maPhieuGiaoHangNhap" OtherKey="maPhieuGiaoHangNhap" Type="PhieuGiaoHangNhap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuGiaoHang" Member="ChiTietPhieuGiaoHangs">
    <Type Name="ChiTietPhieuGiaoHang">
      <Column Name="maPhieuGiao" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="PhieuGiaoHang_ChiTietPhieuGiaoHang" Member="PhieuGiaoHang" ThisKey="maPhieuGiao" OtherKey="maPhieuGiao" Type="PhieuGiaoHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietPhieuGiaoHang" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuNhap" Member="ChiTietPhieuNhaps">
    <Type Name="ChiTietPhieuNhap">
      <Column Name="maPhieuNhap" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNhaCungCap" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="lanNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ChiTietPhieuNhap_ChiTietPhieuGiaoHangNhap" Member="ChiTietPhieuGiaoHangNhaps" ThisKey="maPhieuNhap,maSanPham,maNhaCungCap" OtherKey="maPhieuNhap,maSanPham,maNhaCungCap" Type="ChiTietPhieuGiaoHangNhap" />
      <Association Name="PhieuNhap_ChiTietPhieuNhap" Member="PhieuNhap" ThisKey="maPhieuNhap" OtherKey="maPhieuNhap" Type="PhieuNhap" IsForeignKey="true" />
      <Association Name="SanPham_NhaCungCap_ChiTietPhieuNhap" Member="SanPham_NhaCungCap" ThisKey="maSanPham,maNhaCungCap" OtherKey="maSanPham,maNhaCungCap" Type="SanPham_NhaCungCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuThanhLy" Member="ChiTietPhieuThanhLies">
    <Type Name="ChiTietPhieuThanhLy">
      <Column Name="maThanhLy" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="giaThanhLy" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="PhieuThanhLy_ChiTietPhieuThanhLy" Member="PhieuThanhLy" ThisKey="maThanhLy" OtherKey="maThanhLy" Type="PhieuThanhLy" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietPhieuThanhLy" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GoiSanPham" Member="GoiSanPhams">
    <Type Name="GoiSanPham">
      <Column Name="maGoiSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenGoiSanPham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hinhAnh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="GoiSanPham_ChiTietGoiSanPham" Member="ChiTietGoiSanPhams" ThisKey="maGoiSanPham" OtherKey="maGoiSanPham" Type="ChiTietGoiSanPham" />
    </Type>
  </Table>
  <Table Name="dbo.KhuyenMai" Member="KhuyenMais">
    <Type Name="KhuyenMai">
      <Column Name="maKhuyenMai" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKhuyenMai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="moTa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ngayBatDau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KhuyenMai_KhuyenMaiSanPham" Member="KhuyenMaiSanPhams" ThisKey="maKhuyenMai" OtherKey="maKhuyenMai" Type="KhuyenMaiSanPham" />
    </Type>
  </Table>
  <Table Name="dbo.KhuyenMaiSanPham" Member="KhuyenMaiSanPhams">
    <Type Name="KhuyenMaiSanPham">
      <Column Name="maKhuyenMai" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="phanTramGiam" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KhuyenMai_KhuyenMaiSanPham" Member="KhuyenMai" ThisKey="maKhuyenMai" OtherKey="maKhuyenMai" Type="KhuyenMai" IsForeignKey="true" />
      <Association Name="SanPham_KhuyenMaiSanPham" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiNhanVien" Member="LoaiNhanViens">
    <Type Name="LoaiNhanVien">
      <Column Name="maLoaiNhanVien" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenLoaiNhanVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="LoaiNhanVien_NhanVien" Member="NhanViens" ThisKey="maLoaiNhanVien" OtherKey="maLoaiNhanVien" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiSanPham" Member="LoaiSanPhams">
    <Type Name="LoaiSanPham">
      <Column Name="maLoaiSanPham" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenLoaiSanPham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="LoaiSanPham_SanPham" Member="SanPhams" ThisKey="maLoaiSanPham" OtherKey="maLoaiSanPham" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="maNhaCungCap" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenNhaCungCap" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="soDienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="NhaCungCap_SanPham_NhaCungCap" Member="SanPham_NhaCungCaps" ThisKey="maNhaCungCap" OtherKey="maNhaCungCap" Type="SanPham_NhaCungCap" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maLoaiNhanVien" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tenNhanVien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="soDienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="tenDangNhap" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="matKhau" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="luongCoBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayVaoLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NhanVien_PhieuDoiHang" Member="PhieuDoiHangs" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="PhieuDoiHang" />
      <Association Name="NhanVien_PhieuNhap" Member="PhieuNhaps" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="PhieuNhap" />
      <Association Name="NhanVien_PhieuThanhLy" Member="PhieuThanhLies" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="PhieuThanhLy" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="HoaDon" />
      <Association Name="LoaiNhanVien_NhanVien" Member="LoaiNhanVien" ThisKey="maLoaiNhanVien" OtherKey="maLoaiNhanVien" Type="LoaiNhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDoiHang" Member="PhieuDoiHangs">
    <Type Name="PhieuDoiHang">
      <Column Name="maPhieuDoi" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maHoaDon" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="maKhachHang" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ngayDoi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PhieuDoiHang_ChiTietPhieuDoiHang" Member="ChiTietPhieuDoiHangs" ThisKey="maPhieuDoi" OtherKey="maPhieuDoi" Type="ChiTietPhieuDoiHang" />
      <Association Name="NhanVien_PhieuDoiHang" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="HoaDon_PhieuDoiHang" Member="HoaDon" ThisKey="maHoaDon" OtherKey="maHoaDon" Type="HoaDon" IsForeignKey="true" />
      <Association Name="KhachHang_PhieuDoiHang" Member="KhachHang" ThisKey="maKhachHang" OtherKey="maKhachHang" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuGiaoHang" Member="PhieuGiaoHangs">
    <Type Name="PhieuGiaoHang">
      <Column Name="maPhieuGiao" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maHoaDon" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ngayGiaoDuKien" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="chiPhi" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="tinhTrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PhieuGiaoHang_ChiTietPhieuGiaoHang" Member="ChiTietPhieuGiaoHangs" ThisKey="maPhieuGiao" OtherKey="maPhieuGiao" Type="ChiTietPhieuGiaoHang" />
      <Association Name="HoaDon_PhieuGiaoHang" Member="HoaDon" ThisKey="maHoaDon" OtherKey="maHoaDon" Type="HoaDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuGiaoHangNhap" Member="PhieuGiaoHangNhaps">
    <Type Name="PhieuGiaoHangNhap">
      <Column Name="maPhieuGiaoHangNhap" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayGiao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="soLan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="PhieuGiaoHangNhap_ChiTietPhieuGiaoHangNhap" Member="ChiTietPhieuGiaoHangNhaps" ThisKey="maPhieuGiaoHangNhap" OtherKey="maPhieuGiaoHangNhap" Type="ChiTietPhieuGiaoHangNhap" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhap" Member="PhieuNhaps">
    <Type Name="PhieuNhap">
      <Column Name="maPhieuNhap" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="PhieuNhap_ChiTietPhieuNhap" Member="ChiTietPhieuNhaps" ThisKey="maPhieuNhap" OtherKey="maPhieuNhap" Type="ChiTietPhieuNhap" />
      <Association Name="NhanVien_PhieuNhap" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuThanhLy" Member="PhieuThanhLies">
    <Type Name="PhieuThanhLy">
      <Column Name="maThanhLy" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lyDo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ngayThanhLy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="PhieuThanhLy_ChiTietPhieuThanhLy" Member="ChiTietPhieuThanhLies" ThisKey="maThanhLy" OtherKey="maThanhLy" Type="ChiTietPhieuThanhLy" />
      <Association Name="NhanVien_PhieuThanhLy" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="maSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maLoaiSanPham" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tenSanPham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="donGiaBan" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaySanXuat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hanSuDung" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hinhAnh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SanPham_ChiTietGoiSanPham" Member="ChiTietGoiSanPhams" ThisKey="maSanPham" OtherKey="maSanPham" Type="ChiTietGoiSanPham" />
      <Association Name="SanPham_ChiTietHoaDonSanPham" Member="ChiTietHoaDonSanPhams" ThisKey="maSanPham" OtherKey="maSanPham" Type="ChiTietHoaDonSanPham" />
      <Association Name="SanPham_ChiTietPhieuDoiHang" Member="ChiTietPhieuDoiHangs" ThisKey="maSanPham" OtherKey="maSanPham" Type="ChiTietPhieuDoiHang" />
      <Association Name="SanPham_ChiTietPhieuGiaoHang" Member="ChiTietPhieuGiaoHangs" ThisKey="maSanPham" OtherKey="maSanPham" Type="ChiTietPhieuGiaoHang" />
      <Association Name="SanPham_ChiTietPhieuThanhLy" Member="ChiTietPhieuThanhLies" ThisKey="maSanPham" OtherKey="maSanPham" Type="ChiTietPhieuThanhLy" />
      <Association Name="SanPham_KhuyenMaiSanPham" Member="KhuyenMaiSanPhams" ThisKey="maSanPham" OtherKey="maSanPham" Type="KhuyenMaiSanPham" />
      <Association Name="SanPham_SanPham_NhaCungCap" Member="SanPham_NhaCungCaps" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham_NhaCungCap" />
      <Association Name="SanPham_TonKho" Member="TonKho" ThisKey="maSanPham" OtherKey="maSanPham" Type="TonKho" Cardinality="One" />
      <Association Name="LoaiSanPham_SanPham" Member="LoaiSanPham" ThisKey="maLoaiSanPham" OtherKey="maLoaiSanPham" Type="LoaiSanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham_NhaCungCap" Member="SanPham_NhaCungCaps">
    <Type Name="SanPham_NhaCungCap">
      <Column Name="maSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNhaCungCap" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="donGiaNhap" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="SanPham_NhaCungCap_ChiTietPhieuNhap" Member="ChiTietPhieuNhaps" ThisKey="maSanPham,maNhaCungCap" OtherKey="maSanPham,maNhaCungCap" Type="ChiTietPhieuNhap" />
      <Association Name="NhaCungCap_SanPham_NhaCungCap" Member="NhaCungCap" ThisKey="maNhaCungCap" OtherKey="maNhaCungCap" Type="NhaCungCap" IsForeignKey="true" />
      <Association Name="SanPham_SanPham_NhaCungCap" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TonKho" Member="TonKhos">
    <Type Name="TonKho">
      <Column Name="maSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayCapNhat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="soLuongToiThieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_TonKho" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangThanhVien" Member="HangThanhViens">
    <Type Name="HangThanhVien">
      <Column Name="maHang" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenHang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="mucTieuBatDau" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="mucTieuKetThuc" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="HangThanhVien_UuDaiThanhVien" Member="UuDaiThanhViens" ThisKey="maHang" OtherKey="maHang" Type="UuDaiThanhVien" />
      <Association Name="HangThanhVien_KhachHang" Member="KhachHangs" ThisKey="maHang" OtherKey="maHang" Type="KhachHang" />
    </Type>
  </Table>
  <Table Name="dbo.UuDaiThanhVien" Member="UuDaiThanhViens">
    <Type Name="UuDaiThanhVien">
      <Column Name="maUuDai" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenUuDai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="phanTramGiam" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="maHang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="HangThanhVien_UuDaiThanhVien" Member="HangThanhVien" ThisKey="maHang" OtherKey="maHang" Type="HangThanhVien" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="maHoaDon" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKhachHang" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="maNhanVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="tienDuocGiam" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="tongTienSauGiam" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="HoaDon_ChiTietHoaDonSanPham" Member="ChiTietHoaDonSanPhams" ThisKey="maHoaDon" OtherKey="maHoaDon" Type="ChiTietHoaDonSanPham" />
      <Association Name="HoaDon_PhieuDoiHang" Member="PhieuDoiHangs" ThisKey="maHoaDon" OtherKey="maHoaDon" Type="PhieuDoiHang" />
      <Association Name="HoaDon_PhieuGiaoHang" Member="PhieuGiaoHangs" ThisKey="maHoaDon" OtherKey="maHoaDon" Type="PhieuGiaoHang" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="maKhachHang" OtherKey="maKhachHang" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="maKhachHang" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKhachHang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="soDienThoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="maHang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="diemTichLuy" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ngayCapNhatDiem" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="KhachHang_PhieuDoiHang" Member="PhieuDoiHangs" ThisKey="maKhachHang" OtherKey="maKhachHang" Type="PhieuDoiHang" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="maKhachHang" OtherKey="maKhachHang" Type="HoaDon" />
      <Association Name="HangThanhVien_KhachHang" Member="HangThanhVien" ThisKey="maHang" OtherKey="maHang" Type="HangThanhVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>